volumes:
  kitchen_management_data:
    name: kitchen_management_data
  rabbitmq_data:
    name: rabbitmq_data

networks:
  esd-net:
    driver: bridge
    name: esd-net

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq:/app
    networks:
      - esd-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  ####################################
  # Flask Application: Kitchen Management
  ####################################
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure you have a Dockerfile for the Flask app
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MENU_SERVICE_URL=http://host.docker.internal:5002
      - ORDER_FULFILLMENT_SERVICE_URL=http://host.docker.internal:5020

    volumes:
      - .:/app  # Mount the current directory to the container
      - ./docker_config.py:/app/config.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
  order-fulfillment-service:
    build:
      context: ./order_fulfilment_service
      dockerfile: Dockerfile
    container_name: order-fulfillment-service
    ports:
      - "5020:5020"
    environment:
      - FLASK_ENV=development
      - MENU_SERVICE_URL=http://host.docker.internal:5002
      - KITCHEN_SERVICE_URL=http://host.docker.internal:5008
    volumes:
      - ./order_fulfilment_service:/app
      - ./docker_config.py:/app/config.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
  menu-service:
    build:
      context: ./menu_service
      dockerfile: Dockerfile
    container_name: menu-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - INVENTORY_SERVICE=http://host.docker.internal:5004
      - ERROR_RESOLUTION_SERVICE_URL=http://host.docker.internal:5013
    volumes:
      - ./menu_service:/app
      - ./docker_config.py:/app/config.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
  inventory-service:
    build:
      context: ./inventory_service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=development
      - RABBITMQ_HOST=host.docker.internal
    volumes:
      - ./inventory_service:/app
      - ./docker_config.py:/app/config.py
    networks:
      - esd-net  
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5004/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
  kitchen-station-service:
    build:
      context: ./kitchen_station_service
      dockerfile: Dockerfile
    container_name: kitchen-station-service
    ports:
      - "5008:5008"
    environment:
      - FLASK_ENV=development
     
    volumes:
      - ./kitchen_station_service:/app
      - ./docker_config.py:/app/config.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
  error-resolution-service:
    build:
      context: ./error_resolution_service
      dockerfile: Dockerfile
    container_name: error-resolution-service
    ports:
      - "5013:5013"
    environment:
      - FLASK_ENV=development
      - INVENTORY_SERVICE=http://host.docker.internal:5004
    volumes:
      - ./error_resolution_service:/app
      - ./docker_config.py:/app/config.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
  rfid-scanning-service:
    build:
      context: ./RFID_scanning_service
      dockerfile: Dockerfile
    container_name: rfid-scanning-service
    ports:
      - "5012:5012"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./RFID_scanning_service:/app
      - ./docker_config.py:/app/config.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notification:
    build:
      context: ./feedback_service
      dockerfile: notification_service/Dockerfile
    container_name: notification-service
    environment:
      - RABBITMQ_HOST=host.docker.internal
      - SMTP_SERVER=in-v3.mailjet.com
      - SMTP_PORT=587
      - SMTP_USERNAME=3db3fcf147025c7ab9a24e9e8f75dd62
      - SMTP_PASSWORD=6c0fda3a2887782d20fde64e1c07b043
      - SENDER_EMAIL=yuyaoxuan888@gmail.com
      - RECIPIENT_EMAIL=zjliew.2023@scis.smu.edu.sg
    ports:
      - "5021:5021"
    command: python notification.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5021/health || exit 1"]
      start_period: 45s

  manage_inventory:
    build:
      context: ./manage_inventory_service
      dockerfile: Dockerfile
    container_name: manage-inventory-service
    ports:
      - "5006:5006"  
    environment:
      - RABBITMQ_HOST=host.docker.internal
      - INVENTORY_SERVICE_URL=http://host.docker.internal:5004
    volumes:
      - ./manage_inventory_service:/app
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq
      - inventory-service

  restocking:
    build:
      context: ./restocking_service
      dockerfile: Dockerfile
    container_name: restocking-service
    ports:
      - "5007:5007"
    environment:
      - RABBITMQ_HOST=host.docker.internal
    volumes:
      - ./restocking_service:/app
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy

  ####################################
  # Supplier Services
  ####################################
  supplier_cheesehaven:
    build:
      context: ./supplier_cheesehaven_service
      dockerfile: Dockerfile
    container_name: supplier-cheesehaven
    ports:
      - "5014:5014"
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  supplier_dairydelight:
    build:
      context: ./supplier_dairydelight_service
      dockerfile: Dockerfile
    container_name: supplier-dairydelight
    ports:
      - "5015:5015"
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  supplier_freshfarms:
    build:
      context: ./supplier_freshfarms_service
      dockerfile: Dockerfile
    container_name: supplier-freshfarms
    ports:
      - "5016:5016"
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  supplier_lettuceland:
    build:
      context: ./supplier_lettuceland_service
      dockerfile: Dockerfile
    container_name: supplier-lettuceland
    ports:
      - "5017:5017"
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  supplier_organicgoods:
    build:
      context: ./supplier_organicgoods_service
      dockerfile: Dockerfile
    container_name: supplier-organicgoods
    ports:
      - "5018:5018"
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  supplier_tomatoexpress:
    build:
      context: ./supplier_tomatoexpress_service
      dockerfile: Dockerfile
    container_name: supplier-tomatoexpress
    ports:
      - "5019:5019"
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"