# Custom network
networks:
  esd-net:  
    driver: bridge

services:

  # order_service:
  #   build:
  #     context: .  # Change the context to the root of the project
  #     dockerfile: order_service/Dockerfile
  #   environment:
  #     dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/is213_order
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - esd-net


  feedback_service:
    build:
      context: .  # Change the context to the root of the project
      dockerfile: feedback_service/Dockerfile
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/is213_feedback
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
    networks:
      - esd-net

  submit_feedback_service:
    build:
      context: .  # Change the context to the root of the project
      dockerfile: submit_feedback_service/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - feedback_service
      
    networks:
        - esd-net


  aggregator:
    build:
      context: .  # Change the context to the root of the project
      dockerfile: aggregator/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=feedback_alert
    depends_on:
      - feedback_service
    command: python aggregator.py  # Make sure this matches your script filename
    networks:
        - esd-net

  notification:
    build:
      context: .  # Change the context to the root of the project
      dockerfile: notification_service/Dockerfile
    environment:
      - SMTP_SERVER=in-v3.mailjet.com
      - SMTP_PORT=587
      - SMTP_USERNAME=3db3fcf147025c7ab9a24e9e8f75dd62
      - SMTP_PASSWORD=6c0fda3a2887782d20fde64e1c07b043
      - SENDER_EMAIL=yuyaoxuan888@gmail.com
      - RECIPIENT_EMAIL=zjliew.2023@scis.smu.edu.sg
    ports:
      - "5006:5006"
    depends_on:
      - aggregator
    command: python notification.py  # Ensure this matches the filename of your notification script
    networks:
        - esd-net
