version: "3.8"

# Custom network
networks:
  esd-net:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ port
      - "15672:15672"   # Management dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - esd-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  menu-service:
    build:
      context: ../menu_service  # Reference to your parent directory menu_service
      dockerfile: Dockerfile
    container_name: menu-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - INVENTORY_SERVICE=http://host.docker.internal:5004
      - ERROR_RESOLUTION_SERVICE_URL=http://host.docker.internal:5013
    volumes:
      - ../menu_service:/app
      - ../docker_config.py:/app/config.py
    networks:
      - esd-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  feedback_service:
    build:
      context: .  # Local feedback_service folder
      dockerfile: feedback_service/Dockerfile
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/is213_feedback
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
    networks:
      - esd-net

  submit_feedback_service:
    build:
      context: .
      dockerfile: submit_feedback_service/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - feedback_service
      - menu-service
    networks:
      - esd-net

  notification:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    environment:
      - SMTP_SERVER=in-v3.mailjet.com
      - SMTP_PORT=587
      - SMTP_USERNAME=7524d5ed4cf8bafb22a5a59c1d3d7e36
      - SMTP_PASSWORD=b3597116df3387ccb420a5ff8f97c728
      - SENDER_EMAIL=blbx008228@gmail.com
      - RECIPIENT_EMAIL=brian.lim.2023@scis.smu.edu.sg
    ports:
      - "5021:5021"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy
      feedback_service:
        condition: service_started
    command: python notification.py
    networks:
      - esd-net
